networks:
  default: development
  development:
    cmd: ./ganache.sh
    host: http://127.0.0.1
    timeout: 120
    cmd_settings:
        accounts: 10
        evm_version: berlin
        fork: mainnet
        gas_limit: 30000000
        mnemonic: brownie
        port: 8545
compiler:
  solc:
    version: 0.8.6
    remappings:
      - OpenZeppelin/openzeppelin-contracts@4.3.2=./dependencies/OpenZeppelin/openzeppelin-contracts@4.3.2
reports:
  exclude_paths:
    - contracts/test/**/*
  exclude_contracts:
    - AccessControl
    - Ownable
