name: Slither Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.1"

      - name: Install poetry requirements
        run: >
          curl -sSL https://install.python-poetry.org | python - &&
          poetry install

      - name: Run slither
        run: >
          poetry run slither . --sarif results.sarif

    - name: Check results.sarif presence
      if: always()
      id: results
      shell: bash
      run: >
        test -f ./results.sarif && 
        echo '::set-output name=value::true' || 
        echo '::set-output name=value::false'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ steps.results.outputs.value == 'true' }}
        with:
          sarif_file: results.sarif
